export const cardsData = [
  { id: 1, title: "سبحان الله", count: 100, colorClass: "card-blue" },
  { id: 2, title: "الحمد لله", count: 33, colorClass: "card-yellow" },
  { id: 3, title: "لا إله إلا الله", count: 7, colorClass: "card-green" },
  { id: 4, title: "الله أكبر", count: 10, colorClass: "card-pink" },
  { id: 5, title: "سبحان الله وبحمده", count: 100, colorClass: "card-cyan" },
  { id: 6, title: "أستغفر الله", count: 33, colorClass: "card-purple" },
  { id: 7, title: "اللهم صل وسلم على نبينا محمد", count: 10, colorClass: "card-light-yellow" },
  { id: 8, title: "لا حول ولا قوة إلا بالله", count: 33, colorClass: "card-light-green" },
  { id: 9, title: "سبحان الله العظيم", count: 100, colorClass: "card-light-cyan" },
  { id: 10, title: "رضيت بالله رباً", count: 7, colorClass: "card-light-purple" },
  { id: 11, title: "رضيت بالإسلام ديناً", count: 7, colorClass: "card-light-green2" },
  { id: 12, title: "رضيت بمحمد نبياً", count: 7, colorClass: "card-orange" },
  { id: 13, title: "يا حي يا قيوم برحمتك أستغيث", count: 10, colorClass: "card-red" },
  { id: 14, title: "حسبي الله لا إله إلا هو", count: 33, colorClass: "card-purple-light" },
  { id: 15, title: "اللهم إني أسألك الجنة", count: 10, colorClass: "card-teal" },
  { id: 16, title: "اللهم نجني من النار", count: 10, colorClass: "card-gray" },
  { id: 17, title: "اللهم أنت ربي لا إله إلا أنت", count: 7, colorClass: "card-yellow" },
  { id: 18, title: "اللهم اجعلني من التوابين", count: 33, colorClass: "card-brown" },
  { id: 19, title: "اللهم اجعلني من المتطهرين", count: 33, colorClass: "card-indigo" },
  { id: 20, title: "اللهم أعني على ذكرك", count: 10, colorClass: "card-light-orange" },
  { id: 21, title: "اللهم أعني على شكرك", count: 10, colorClass: "card-light-green2" },
  { id: 22, title: "اللهم أعني على حسن عبادتك", count: 10, colorClass: "card-teal-light" },
  { id: 23, title: "اللهم اشرح صدري", count: 33, colorClass: "card-sky" },
  { id: 24, title: "اللهم يسر أمري", count: 33, colorClass: "card-light-orange2" },
  { id: 25, title: "اللهم اجعلني من الحامدين", count: 100, colorClass: "card-light-green" },
  { id: 26, title: "اللهم اجعلني من الشاكرين", count: 100, colorClass: "card-light-purple" },
  { id: 27, title: "اللهم اجعلني من عبادك الصالحين", count: 100, colorClass: "card-green" },
  { id: 28, title: "اللهم ارزقني حسن الخاتمة", count: 10, colorClass: "card-purple-light" },
  { id: 29, title: "اللهم احفظني من بين يدي", count: 10, colorClass: "card-light-orange2" },
  { id: 30, title: "اللهم احفظني من خلفي", count: 10, colorClass: "card-teal" }
];
