export const cardsData = [
  { id: 1, title: "سبحان الله", count: 100, backgroundColor: "#E3F2FD" },
  { id: 2, title: "الحمد لله", count: 33, backgroundColor: "#FFECB3" },
  { id: 3, title: "لا إله إلا الله", count: 7, backgroundColor: "#C8E6C9" },
  { id: 4, title: "الله أكبر", count: 10, backgroundColor: "#F8BBD0" },
  { id: 5, title: "سبحان الله وبحمده", count: 100, backgroundColor: "#B3E5FC" },
  { id: 6, title: "أستغفر الله", count: 33, backgroundColor: "#E1BEE7" },
  { id: 7, title: "اللهم صل وسلم على نبينا محمد", count: 10, backgroundColor: "#FFF9C4" },
  { id: 8, title: "لا حول ولا قوة إلا بالله", count: 33, backgroundColor: "#F0F4C3" },
  { id: 9, title: "سبحان الله العظيم", count: 100, backgroundColor: "#B2EBF2" },
  { id: 10, title: "رضيت بالله رباً", count: 7, backgroundColor: "#D1C4E9" },
  { id: 11, title: "رضيت بالإسلام ديناً", count: 7, backgroundColor: "#DCEDC8" },
  { id: 12, title: "رضيت بمحمد نبياً", count: 7, backgroundColor: "#FFE0B2" },
  { id: 13, title: "يا حي يا قيوم برحمتك أستغيث", count: 10, backgroundColor: "#FFCDD2" },
  { id: 14, title: "حسبي الله لا إله إلا هو", count: 33, backgroundColor: "#F3E5F5" },
  { id: 15, title: "اللهم إني أسألك الجنة", count: 10, backgroundColor: "#E0F2F1" },
  { id: 16, title: "اللهم نجني من النار", count: 10, backgroundColor: "#F5F5F5" },
  { id: 17, title: "اللهم أنت ربي لا إله إلا أنت", count: 7, backgroundColor: "#FFECB3" },
  { id: 18, title: "اللهم اجعلني من التوابين", count: 33, backgroundColor: "#D7CCC8" },
  { id: 19, title: "اللهم اجعلني من المتطهرين", count: 33, backgroundColor: "#C5CAE9" },
  { id: 20, title: "اللهم أعني على ذكرك", count: 10, backgroundColor: "#FFF3E0" },
  { id: 21, title: "اللهم أعني على شكرك", count: 10, backgroundColor: "#DCEDC8" },
  { id: 22, title: "اللهم أعني على حسن عبادتك", count: 10, backgroundColor: "#B2DFDB" },
  { id: 23, title: "اللهم اشرح صدري", count: 33, backgroundColor: "#E1F5FE" },
  { id: 24, title: "اللهم يسر أمري", count: 33, backgroundColor: "#FFCCBC" },
  { id: 25, title: "اللهم اجعلني من الحامدين", count: 100, backgroundColor: "#F0F4C3" },
  { id: 26, title: "اللهم اجعلني من الشاكرين", count: 100, backgroundColor: "#D1C4E9" },
  { id: 27, title: "اللهم اجعلني من عبادك الصالحين", count: 100, backgroundColor: "#C8E6C9" },
  { id: 28, title: "اللهم ارزقني حسن الخاتمة", count: 10, backgroundColor: "#F3E5F5" },
  { id: 29, title: "اللهم احفظني من بين يدي", count: 10, backgroundColor: "#FFCCBC" },
  { id: 30, title: "اللهم احفظني من خلفي", count: 10, backgroundColor: "#E0F2F1" }
];
